import { Request, Response } from 'express';
import { GamingSession, Location, LocationAction } from '@database/models';
import { logger } from '../utils/logger';
import { successResponse, errorResponse, getRequestId } from '../utils/apiResponse';

export class QuestController {
  /**
   * Create or update quest (using GamingSession)
   * POST /game/quests
   */
  static async createQuest(req: Request, res: Response): Promise<void> {
    try {
      const character = req.character;
      if (!character) {
        res.status(401).json(errorResponse(
          'Character context required',
          'CHARACTER_CONTEXT_REQUIRED',
          undefined,
          401,
          getRequestId(req)
        ));
        return;
      }

      // Check if user is master
      const isMaster = character.gameplayRoles?.includes('master') || 
                       character.gameplayRoles?.includes('gestore');
      if (!isMaster) {
        res.status(403).json(errorResponse(
          'Only masters can create quests',
          'INSUFFICIENT_PERMISSIONS',
          undefined,
          403,
          getRequestId(req)
        ));
        return;
      }

      const {
        locationId,
        title,
        description,
        participantIds,
        turnOrder
      } = req.body;

      if (!locationId || !title) {
        res.status(400).json(errorResponse(
          'locationId and title are required',
          'MISSING_REQUIRED_FIELDS',
          undefined,
          400,
          getRequestId(req)
        ));
        return;
      }

      // Check if location exists
      const location = await Location.findById(locationId);
      if (!location) {
        res.status(404).json(errorResponse(
          'Location not found',
          'LOCATION_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Create or update GamingSession for quest
      const sessionData: any = {
        title,
        description: description || '',
        masterId: character.characterId,
        masterName: character.characterName,
        sessionDate: new Date(),
        startTime: new Date(),
        primaryLocation: locationId,
        sessionType: 'event',
        difficultyLevel: 'medium',
        status: 'active',
        currentQuestStatus: 'planning',
        participants: participantIds?.map((id: string, index: number) => ({
          characterId: id,
          characterName: '', // Will be populated
          joinedAt: new Date(),
          wasActive: true,
          participationScore: 5
        })) || [],
        turnOrder: turnOrder || participantIds || [],
        actionModeActive: false
      };

      // Check if there's an existing active quest for this location
      const existingSession = await GamingSession.findOne({
        primaryLocation: locationId,
        status: 'active',
        currentQuestStatus: { $in: ['planning', 'active'] }
      });

      let session;
      if (existingSession) {
        // Update existing session
        Object.assign(existingSession, sessionData);
        await existingSession.save();
        session = existingSession;
      } else {
        // Create new session
        session = await GamingSession.create(sessionData);
      }

      // Update location's active session
      location.activeSession = {
        sessionId: session._id,
        startedAt: new Date(),
        lastActivityAt: new Date(),
        expiresAt: new Date(Date.now() + 3 * 60 * 60 * 1000), // 3 hours
        isAutoGenerated: false,
        participantIds: participantIds || []
      };
      await location.save();

      logger.info(`Quest created/updated: ${session._id} by ${character.characterName}`);

      res.json(successResponse(
        { quest: session },
        undefined,
        getRequestId(req)
      ));
    } catch (error: any) {
      const err = error as Error;
      logger.error('Create quest error:', {
        message: err.message,
        stack: err.stack
      });
      res.status(500).json(errorResponse(
        'Failed to create quest',
        'CREATE_QUEST_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  /**
   * Start quest
   * POST /game/quests/:questId/start
   */
  static async startQuest(req: Request<{ questId: string }>, res: Response): Promise<void> {
    try {
      const character = req.character;
      if (!character) {
        res.status(401).json(errorResponse(
          'Character context required',
          'CHARACTER_CONTEXT_REQUIRED',
          undefined,
          401,
          getRequestId(req)
        ));
        return;
      }

      const { questId } = req.params;

      const session = await GamingSession.findById(questId);
      if (!session) {
        res.status(404).json(errorResponse(
          'Quest not found',
          'QUEST_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Check permissions
      const isMaster = character.gameplayRoles?.includes('master') || 
                       character.gameplayRoles?.includes('gestore');
      const isOwner = session.masterId.toString() === character.characterId;
      
      if (!isMaster && !isOwner) {
        res.status(403).json(errorResponse(
          'Only the quest master can start the quest',
          'INSUFFICIENT_PERMISSIONS',
          undefined,
          403,
          getRequestId(req)
        ));
        return;
      }

      session.status = 'active';
      session.currentQuestStatus = 'active';
      await session.save();

      logger.info(`Quest started: ${questId} by ${character.characterName}`);

      res.json(successResponse(
        { quest: session },
        undefined,
        getRequestId(req)
      ));
    } catch (error: any) {
      const err = error as Error;
      logger.error('Start quest error:', {
        message: err.message,
        stack: err.stack
      });
      res.status(500).json(errorResponse(
        'Failed to start quest',
        'START_QUEST_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  /**
   * End quest
   * POST /game/quests/:questId/end
   */
  static async endQuest(req: Request<{ questId: string }>, res: Response): Promise<void> {
    try {
      const character = req.character;
      if (!character) {
        res.status(401).json(errorResponse(
          'Character context required',
          'CHARACTER_CONTEXT_REQUIRED',
          undefined,
          401,
          getRequestId(req)
        ));
        return;
      }

      const { questId } = req.params;

      const session = await GamingSession.findById(questId);
      if (!session) {
        res.status(404).json(errorResponse(
          'Quest not found',
          'QUEST_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Check permissions
      const isMaster = character.gameplayRoles?.includes('master') || 
                       character.gameplayRoles?.includes('gestore');
      const isOwner = session.masterId.toString() === character.characterId;
      
      if (!isMaster && !isOwner) {
        res.status(403).json(errorResponse(
          'Only the quest master can end the quest',
          'INSUFFICIENT_PERMISSIONS',
          undefined,
          403,
          getRequestId(req)
        ));
        return;
      }

      session.status = 'completed';
      session.currentQuestStatus = 'completed';
      session.endTime = new Date();
      session.actionModeActive = false;
      await session.save();

      logger.info(`Quest ended: ${questId} by ${character.characterName}`);

      res.json(successResponse(
        { quest: session },
        undefined,
        getRequestId(req)
      ));
    } catch (error: any) {
      const err = error as Error;
      logger.error('End quest error:', {
        message: err.message,
        stack: err.stack
      });
      res.status(500).json(errorResponse(
        'Failed to end quest',
        'END_QUEST_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  /**
   * Activate action mode (10 minutes timer)
   * POST /game/quests/:questId/action-mode
   */
  static async activateActionMode(req: Request<{ questId: string }>, res: Response): Promise<void> {
    try {
      const character = req.character;
      if (!character) {
        res.status(401).json(errorResponse(
          'Character context required',
          'CHARACTER_CONTEXT_REQUIRED',
          undefined,
          401,
          getRequestId(req)
        ));
        return;
      }

      const { questId } = req.params;

      const session = await GamingSession.findById(questId);
      if (!session) {
        res.status(404).json(errorResponse(
          'Quest not found',
          'QUEST_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Check permissions
      const isMaster = character.gameplayRoles?.includes('master') || 
                       character.gameplayRoles?.includes('gestore');
      const isOwner = session.masterId.toString() === character.characterId;
      
      if (!isMaster && !isOwner) {
        res.status(403).json(errorResponse(
          'Only the quest master can activate action mode',
          'INSUFFICIENT_PERMISSIONS',
          undefined,
          403,
          getRequestId(req)
        ));
        return;
      }

      // Set action mode active for 10 minutes
      const now = new Date();
      const tenMinutesLater = new Date(now.getTime() + 10 * 60 * 1000);

      session.actionModeActive = true;
      session.actionModeEndsAt = tenMinutesLater;
      session.lastMasterScreenAt = now;
      await session.save();

      // Emit WebSocket event
      const io = req.app.get('io');
      if (io) {
        const roomName = `location_${session.primaryLocation}`;
        io.to(roomName).emit('action_mode_activated', {
          questId: session._id,
          endsAt: tenMinutesLater,
          locationId: session.primaryLocation
        });
      }

      logger.info(`Action mode activated: ${questId} by ${character.characterName}, ends at ${tenMinutesLater}`);

      res.json(successResponse(
        {
          quest: session,
          actionModeEndsAt: tenMinutesLater
        },
        undefined,
        getRequestId(req)
      ));
    } catch (error: any) {
      const err = error as Error;
      logger.error('Activate action mode error:', {
        message: err.message,
        stack: err.stack
      });
      res.status(500).json(errorResponse(
        'Failed to activate action mode',
        'ACTIVATE_ACTION_MODE_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  /**
   * Reveal all hidden actions (end action mode)
   * POST /game/quests/:questId/reveal-actions
   */
  static async revealActions(req: Request<{ questId: string }>, res: Response): Promise<void> {
    try {
      const character = req.character;
      if (!character) {
        res.status(401).json(errorResponse(
          'Character context required',
          'CHARACTER_CONTEXT_REQUIRED',
          undefined,
          401,
          getRequestId(req)
        ));
        return;
      }

      const { questId } = req.params;

      const session = await GamingSession.findById(questId);
      if (!session) {
        res.status(404).json(errorResponse(
          'Quest not found',
          'QUEST_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Check permissions
      const isMaster = character.gameplayRoles?.includes('master') || 
                       character.gameplayRoles?.includes('gestore');
      const isOwner = session.masterId.toString() === character.characterId;
      
      if (!isMaster && !isOwner) {
        res.status(403).json(errorResponse(
          'Only the quest master can reveal actions',
          'INSUFFICIENT_PERMISSIONS',
          undefined,
          403,
          getRequestId(req)
        ));
        return;
      }

      // Reveal all hidden actions for this location
      const now = new Date();
      await LocationAction.updateMany(
        {
          locationId: session.primaryLocation.toString(),
          isHidden: true,
          revealedAt: { $exists: false }
        },
        {
          $set: { revealedAt: now }
        }
      );

      // Deactivate action mode
      session.actionModeActive = false;
      await session.save();

      // Emit WebSocket event
      const io = req.app.get('io');
      if (io) {
        const roomName = `location_${session.primaryLocation}`;
        io.to(roomName).emit('actions_revealed', {
          questId: session._id,
          locationId: session.primaryLocation,
          revealedAt: now
        });
      }

      logger.info(`Actions revealed: ${questId} by ${character.characterName}`);

      res.json(successResponse(
        { revealed: true },
        undefined,
        getRequestId(req)
      ));
    } catch (error: any) {
      const err = error as Error;
      logger.error('Reveal actions error:', {
        message: err.message,
        stack: err.stack
      });
      res.status(500).json(errorResponse(
        'Failed to reveal actions',
        'REVEAL_ACTIONS_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  /**
   * Get quest status
   * GET /game/quests/:questId
   */
  static async getQuestStatus(req: Request<{ questId: string }>, res: Response): Promise<void> {
    try {
      const character = req.character;
      if (!character) {
        res.status(401).json(errorResponse(
          'Character context required',
          'CHARACTER_CONTEXT_REQUIRED',
          undefined,
          401,
          getRequestId(req)
        ));
        return;
      }

      const { questId } = req.params;

      const session = await GamingSession.findById(questId)
        .populate('primaryLocation', 'name')
        .populate('participants.characterId', 'name');

      if (!session) {
        res.status(404).json(errorResponse(
          'Quest not found',
          'QUEST_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      res.json(successResponse(
        { quest: session },
        undefined,
        getRequestId(req)
      ));
    } catch (error: any) {
      const err = error as Error;
      logger.error('Get quest status error:', {
        message: err.message,
        stack: err.stack
      });
      res.status(500).json(errorResponse(
        'Failed to get quest status',
        'GET_QUEST_STATUS_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }
}

