import { Request, Response } from 'express';
import { Character } from '@database/models/Character';
import { Location } from '@database/models/Location';
import { Item, ShopItem, CharacterInventory } from '../models/Item';
import { getCharacterFinancesSnapshot, deductCash, deductCredit } from '@features/economia/api';
import { getCorporationTreasuryRaw, debitTreasuryUnsafe } from '@features/corporazioni/api';
import { logger } from '@modules/game/logger';
import { successResponse, errorResponse, getRequestId } from '@shared/utils/apiResponse';

// Rinominato da EconomyController.ts (Fase 6.4): dopo lo split di Fase 6.3
// (Financial/Services estratti in features/economia) questo file contiene solo
// le 4 route dello shop generale/di location — "Economy" non descriveva più
// cosa c'è dentro.
export class ShopController {
  /**
   * GET /game/economy/general-store
   * Get all public items from the general catalog (London)
   * This is cache-friendly and returns base items, not shop-specific data
   */
  static async getGeneralStore(req: Request, res: Response): Promise<void> {
    try {
      const characterId = req.character?.characterId;

      // Get character if authenticated
      let character = null;
      let finances = null;

      if (characterId) {
        character = await Character.findById(characterId);
        if (!character) {
          res.status(404).json(errorResponse(
            'Personaggio non trovato',
            'CHARACTER_NOT_FOUND',
            undefined,
            404,
            getRequestId(req)
          ));
          return;
        }

        finances = await getCharacterFinancesSnapshot(characterId);
      }

      // Get all public items
      const items = await Item.find({ isPublic: true })
        .select('name description category subcategory basePrice properties prerequisites financialSettings image imageUrl')
        .lean();

      // Format with financial info if authenticated
      const formattedItems = items.map((item: any) => {
        // Create item object with 'requirements' field for meetsRequirements compatibility
        // Map prerequisites field names to match meetsRequirements expectations
        const itemWithRequirements = {
          ...item,
          requirements: {
            occupations: item.prerequisites?.requiredOccupations || [],
            corporations: item.prerequisites?.requiredCorporations || [],
            skills: item.prerequisites?.minimumSkills || {},
            socialClass: item.prerequisites?.requiredSocialClass || [],
            financialClasses: item.prerequisites?.requiredFinancialClasses || []
          }
        };

        return {
          id: item._id,
          name: item.name,
          description: item.description,
          category: item.category,
          subcategory: item.subcategory,
          price: item.basePrice,
          priceFormatted: ShopController.formatCurrency(item.basePrice),
          properties: item.properties,
          requirements: item.prerequisites,
          // imageUrl (CDN, manual upload) takes precedence; image is the static filename
          // generated by local-tools/imagegen into apps/game/public/artifacts/items/
          imageUrl: item.imageUrl || (item.image ? `/artifacts/items/${item.image}` : null),

          // Add financial info if character authenticated
          ...(finances && character && {
            canPurchase: ShopController.meetsRequirements(itemWithRequirements, character),
            canPurchaseWithCash: (finances.cash + finances.bankDeposit) >= item.basePrice,
            canPurchaseWithCredit: ShopController.canPurchaseWithCredit(itemWithRequirements, finances, item.basePrice),
            creditEligible: item.financialSettings?.eligibleForCredit || false,
            socialClasses: item.financialSettings?.socialClassesEligible || []
          })
        };
      });

      res.json(successResponse(
        {
          items: formattedItems,
          ...(finances && {
            character: {
              finances: {
                cash: finances.cash,
                bankDeposit: finances.bankDeposit,
                totalWealth: finances.cash + finances.bankDeposit,
                socialClass: finances.socialClass,
                creditLine: {
                  maxWeekly: finances.creditLine.maxWeekly,
                  currentAvailable: finances.creditLine.currentAvailable,
                  nextResetDate: finances.creditLine.nextResetDate
                }
              }
            }
          })
        },
        undefined,
        getRequestId(req)
      ));

    } catch (error: unknown) {
      const err = error as Error;
      logger.error('Get general store error:', {
        error: err.message,
        stack: err.stack,
        name: err.name,
        characterId: req.character?.characterId,
        params: req.params,
        query: req.query
      });

      res.status(500).json(errorResponse(
        'Impossibile recuperare il catalogo generale',
        'GENERAL_STORE_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  /**
   * POST /game/economy/general-store/:itemId/purchase
   * Buy a public general-store item, paying either from cash+bankDeposit or
   * from the weekly credit line.
   * Body: { paymentMethod: 'cash' | 'credit' }
   */
  static async purchaseItem(req: Request<{ itemId: string }>, res: Response): Promise<void> {
    try {
      const { itemId } = req.params;
      const { paymentMethod } = req.body as { paymentMethod?: 'cash' | 'credit' };
      const characterId = req.character!.characterId;

      if (paymentMethod !== 'cash' && paymentMethod !== 'credit') {
        res.status(400).json(errorResponse(
          'paymentMethod deve essere "cash" o "credit"',
          'INVALID_PAYMENT_METHOD',
          undefined,
          400,
          getRequestId(req)
        ));
        return;
      }

      const [character, item, finances] = await Promise.all([
        Character.findById(characterId),
        Item.findOne({ _id: itemId, isPublic: true }).lean(),
        getCharacterFinancesSnapshot(characterId)
      ]);

      if (!character) {
        res.status(404).json(errorResponse('Personaggio non trovato', 'CHARACTER_NOT_FOUND', undefined, 404, getRequestId(req)));
        return;
      }
      if (!item) {
        res.status(404).json(errorResponse('Oggetto non trovato', 'ITEM_NOT_FOUND', undefined, 404, getRequestId(req)));
        return;
      }
      if (!finances) {
        res.status(404).json(errorResponse('Finanze del personaggio non trovate', 'FINANCES_NOT_FOUND', undefined, 404, getRequestId(req)));
        return;
      }

      const itemWithRequirements = {
        ...item,
        requirements: {
          occupations: item.prerequisites?.requiredOccupations || [],
          corporations: item.prerequisites?.requiredCorporations || [],
          skills: item.prerequisites?.minimumSkills || {},
          socialClass: item.prerequisites?.requiredSocialClass || [],
          financialClasses: item.prerequisites?.requiredFinancialClasses || []
        }
      };

      if (!ShopController.meetsRequirements(itemWithRequirements, character)) {
        res.status(403).json(errorResponse('Requisiti non soddisfatti per questo oggetto', 'REQUIREMENTS_NOT_MET', undefined, 403, getRequestId(req)));
        return;
      }

      const price = item.basePrice;

      if (paymentMethod === 'cash') {
        const result = await deductCash(characterId, price);
        if (!result.ok) {
          if (result.reason === 'NOT_FOUND') {
            res.status(404).json(errorResponse('Finanze del personaggio non trovate', 'FINANCES_NOT_FOUND', undefined, 404, getRequestId(req)));
            return;
          }
          res.status(400).json(errorResponse(
            'Fondi insufficienti',
            'INSUFFICIENT_FUNDS',
            { required: price, available: result.available },
            400,
            getRequestId(req)
          ));
          return;
        }
      } else {
        if (!item.financialSettings?.eligibleForCredit) {
          res.status(403).json(errorResponse('Oggetto non acquistabile a credito', 'CREDIT_NOT_ELIGIBLE', undefined, 403, getRequestId(req)));
          return;
        }
        if (!ShopController.canPurchaseBySocialClass(itemWithRequirements, finances.socialClass)) {
          res.status(403).json(errorResponse('La classe sociale del personaggio non permette questo acquisto a credito', 'SOCIAL_CLASS_INELIGIBLE', undefined, 403, getRequestId(req)));
          return;
        }

        const result = await deductCredit(characterId, price);
        if (!result.ok) {
          if (result.reason === 'NOT_FOUND') {
            res.status(404).json(errorResponse('Finanze del personaggio non trovate', 'FINANCES_NOT_FOUND', undefined, 404, getRequestId(req)));
            return;
          }
          res.status(400).json(errorResponse(
            'Credito settimanale insufficiente',
            'INSUFFICIENT_CREDIT',
            { required: price, available: result.available },
            400,
            getRequestId(req)
          ));
          return;
        }
      }

      let inventory = await CharacterInventory.findOne({ characterId });
      if (!inventory) {
        inventory = new CharacterInventory({ characterId, items: [], lastUpdated: new Date() });
      }
      (inventory as any).addItem(item._id, 1, 'purchase');
      await inventory.save();

      const updatedFinances = await getCharacterFinancesSnapshot(characterId);

      logger.info('Item purchased', { characterId, itemId, paymentMethod, price });

      res.json(successResponse(
        {
          finances: updatedFinances && {
            cash: updatedFinances.cash,
            bankDeposit: updatedFinances.bankDeposit,
            totalWealth: updatedFinances.cash + updatedFinances.bankDeposit,
            creditLine: {
              maxWeekly: updatedFinances.creditLine.maxWeekly,
              currentAvailable: updatedFinances.creditLine.currentAvailable
            }
          },
          purchasedItem: {
            id: item._id,
            name: item.name,
            price,
            priceFormatted: ShopController.formatCurrency(price)
          }
        },
        undefined,
        getRequestId(req)
      ));

    } catch (error: unknown) {
      const err = error as Error;
      logger.error('Purchase item error:', {
        error: err.message,
        stack: err.stack,
        name: err.name,
        characterId: req.character?.characterId,
        itemId: req.params?.itemId,
        requestBody: req.body
      });

      res.status(500).json(errorResponse(
        'Impossibile completare l\'acquisto',
        'PURCHASE_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  /**
   * GET /game/economy/shops/:locationId
   * Get shop items for a location with access filtering and financial options
   * Query params: filter (credit_only|all)
   */
  static async getShopItems(req: Request<{ locationSlug: string }>, res: Response): Promise<void> {
    try {
      const { locationSlug } = req.params;
      const { filter = 'all' } = req.query;
      const characterId = req.character!.characterId;

      // Get character
      const character = await Character.findById(characterId);
      if (!character) {
        res.status(404).json(errorResponse(
          'Personaggio non trovato',
          'CHARACTER_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Try to find location by ID, then by slug
      const location = await Location.findOne({ slug: locationSlug });
      if (!location) {
        res.status(404).json(errorResponse(
          'Location non trovata',
          'LOCATION_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Check location access
      if (locationSlug !== 'london') {
        const hasAccess = await ShopController.checkLocationAccess(location, character);
        if (!hasAccess) {
          res.status(404).json(errorResponse(
            'Accesso alla location non valido',
            'INVALID_LOCATION_ACCESS',
            undefined,
            404,
            getRequestId(req)
          ));
          return;
        }

        // Check if shop is enabled
        if (!location.settings.shop) {
          res.status(404).json(errorResponse(
            'Negozio non trovato',
            'SHOP_NOT_FOUND',
            undefined,
            404,
            getRequestId(req)
          ));
          return;
        }
      }

      // Get character finances
      const finances = await getCharacterFinancesSnapshot(characterId);

      // Get shop items with item details populated
      let allItems = [];
      if (locationSlug === 'london') {
        allItems = await ShopItem.find({}).populate('itemId');
      } else {
        allItems = await ShopItem.find({ locationId: location._id }).populate('itemId');
      }

      // Filter by character permissions and visibility
      let availableItems = allItems.filter((item: any) =>
        ShopController.canPurchaseItem(item, character)
      );

      // Apply financial filtering
      if (finances && filter === 'credit_only') {
        // First filter: show only items that are credit-eligible
        availableItems = availableItems.filter((shopItem: any) => {
          const item = shopItem.itemId;
          return item.financialSettings?.eligibleForCredit === true;
        });

        // Second filter: apply social class filtering
        availableItems = availableItems.filter((shopItem: any) =>
          ShopController.canPurchaseBySocialClass(shopItem.itemId, finances.socialClass)
        );

        // Third filter: check if affordable with credit
        availableItems = availableItems.filter((shopItem: any) => {
          const canAffordWithCredit = finances.creditLine?.currentAvailable >= shopItem.price;
          return canAffordWithCredit;
        });
      }

      // Format items with financial info
      const itemsWithFinancialInfo = availableItems.map((shopItem: any) => {
        const item = shopItem.itemId;
        return {
          id: shopItem._id,
          itemId: item._id,
          name: item.name,
          description: item.description,
          price: shopItem.price,
          priceFormatted: ShopController.formatCurrency(shopItem.price),
          inStock: shopItem.currentStock > 0,
          currentStock: shopItem.currentStock,
          maxStock: shopItem.maxStock,
          category: item.category || 'General',
          requirements: item.prerequisites,
          canPurchase: ShopController.meetsRequirements(item, character),
          // Financial info if available
          ...(finances && {
            canPurchaseWithCash: (finances.cash + finances.bankDeposit) >= shopItem.price,
            canPurchaseWithCredit: ShopController.canPurchaseWithCredit(item, finances, shopItem.price),
            creditEligible: item.financialSettings?.eligibleForCredit || false,
            socialClasses: item.financialSettings?.socialClassesEligible || []
          })
        };
      });

      res.json(successResponse(
        {
          location: {
            id: location._id,
            name: location.name,
            slug: location.slug,
            description: location.description
          },
          shop: {
            items: itemsWithFinancialInfo
          },
          // Include character financial info if available
          ...(finances && {
            character: {
              finances: {
                cash: finances.cash,
                bankDeposit: finances.bankDeposit,
                totalWealth: finances.cash + finances.bankDeposit,
                socialClass: finances.socialClass,
                creditLine: {
                  maxWeekly: finances.creditLine.maxWeekly,
                  currentAvailable: finances.creditLine.currentAvailable,
                  nextResetDate: finances.creditLine.nextResetDate
                }
              }
            }
          }),
          filters: {
            current: filter,
            available: ['all', 'credit_only']
          }
        },
        undefined,
        getRequestId(req)
      ));

    } catch (error: unknown) {
      const err = error as Error;
      logger.error('Get shop items error:', {
        error: err.message,
        stack: err.stack,
        name: err.name,
        characterId: req.character?.characterId,
        locationSlug: req.params?.locationSlug,
        filter: req.query?.filter,
        params: req.params,
        query: req.query
      });

      res.status(500).json(errorResponse(
        'Impossibile recuperare gli articoli del negozio',
        'SHOP_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  /**
   * Check if item can be purchased with credit line
   */
  private static canPurchaseWithCredit(item: any, finances: any, price?: number): boolean {
    if (!item.financialSettings?.eligibleForCredit) return false;
    const itemPrice = price || item.basePrice;
    return finances.creditLine.currentAvailable >= itemPrice;
  }

  /**
   * Map internal English social class names to item class names for compatibility
   */
  private static mapSocialClassToItemClass(characterSocialClass: string): string {
    const classMapping: { [key: string]: string } = {
      'destitute': 'Lower Class',
      'poor': 'Lower Class',
      'modest': 'Working Class',
      'lower_middle': 'Middle Class',
      'middle_class': 'Middle Class',
      'wealthy': 'Upper Class',
      'affluent': 'Upper Class',
      'elite': 'Upper Class'
    };

    return classMapping[characterSocialClass] || characterSocialClass;
  }

  /**
   * Check if character's social class can purchase item
   */
  private static canPurchaseBySocialClass(item: any, characterSocialClass: string): boolean {
    // If item has no social class restrictions, everyone can buy
    if (!item.financialSettings?.socialClassesEligible || item.financialSettings.socialClassesEligible.length === 0) {
      return true;
    }

    // Map character's Italian class name to English item class name
    const mappedClass = ShopController.mapSocialClassToItemClass(characterSocialClass);

    // Check if mapped social class is in allowed list
    return item.financialSettings.socialClassesEligible.includes(mappedClass);
  }

  /**
   * POST /game/economy/shops/:shopId/restock
   * Restock shop items (corporation officers only)
   */
  static async restockShop(req: Request<{ shopId: string }>, res: Response): Promise<void> {
    try {
      const { shopId } = req.params;
      const { itemId, quantity, payFromTreasury } = req.body;
      const characterId = req.character!.characterId;

      // Bug preesistente preservato esattamente, trovato in test E2E su Docker
      // (Fase 6.4): Character non ha un campo/virtual "corporations" nello
      // schema — .populate('corporations') lancia sempre StrictPopulateError
      // ("Cannot populate path `corporations` because it is not in your
      // schema"), quindi restockShop restituisce sempre 500 RESTOCK_ERROR per
      // qualunque richiesta, prima ancora di arrivare al controllo di
      // membership o ai bug 1/2 sul tesoro/prerequisiti sotto — endpoint di
      // fatto non funzionante, comportamento identico a prima dello
      // spostamento in features/oggetti (stesso codice verbatim).
      const character = await Character.findById(characterId).populate('corporations');
      if (!character) {
        res.status(404).json(errorResponse(
          'Personaggio non trovato',
          'CHARACTER_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Get shop location and verify corporation ownership
      const location = await Location.findById(shopId);
      if (!location || !location.corporationId) {
        res.status(404).json(errorResponse(
          'Shop not found',
          'SHOP_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Check if character is corporation officer
      const isCorporationMember = character.corporations.some(
        (corp: any) => corp.id.toString() === location.corporationId.toString()
      );

      if (!isCorporationMember) {
        res.status(403).json(errorResponse(
          'Accesso negato',
          'ACCESS_DENIED',
          undefined,
          403,
          getRequestId(req)
        ));
        return;
      }

      // Get item and corporation (lettura non mutante del tesoro: serve comunque
      // per verificarne l'esistenza e, se non si paga dal tesoro, per i campi
      // "treasury" della risposta — vedi sotto)
      const [item, treasuryPeek] = await Promise.all([
        ShopItem.findOne({ _id: itemId, locationId: shopId }),
        getCorporationTreasuryRaw(location.corporationId)
      ]);

      if (!item || !treasuryPeek.found) {
        res.status(404).json(errorResponse(
          'Articolo o corporazione non trovata',
          'ITEM_NOT_FOUND',
          undefined,
          404,
          getRequestId(req)
        ));
        return;
      }

      // Calculate restock cost
      const restockCost = item.basePrice ? item.basePrice * quantity : item.price * quantity * 0.7; // 30% margin

      // Bug preesistente preservato esattamente (vedi features/corporazioni/api.ts,
      // debitTreasuryUnsafe/getCorporationTreasuryRaw): corporation.treasury è un
      // oggetto, non un numero. Se si paga dal tesoro il campo viene corrotto a
      // NaN; se non si paga, la risposta comunque ricostruisce previousBalance/
      // newBalance dal valore corrente (qui non mutato, quindi ancora l'oggetto
      // grezzo) — in entrambi i casi il comportamento è identico a prima dello
      // spostamento in features/oggetti.
      let treasuryValue: unknown;
      if (payFromTreasury) {
        const debit = await debitTreasuryUnsafe(location.corporationId, restockCost);
        if (!debit.ok) {
          res.status(404).json(errorResponse(
            'Articolo o corporazione non trovata',
            'ITEM_NOT_FOUND',
            undefined,
            404,
            getRequestId(req)
          ));
          return;
        }
        treasuryValue = debit.treasury;
      } else {
        treasuryValue = treasuryPeek.treasury;
      }

      // Update item stock
      item.currentStock = Math.min(item.currentStock + quantity, item.maxStock);
      await item.save();

      logger.info('Shop restocked', {
        shopId,
        itemId,
        quantityAdded: quantity,
        costPaid: restockCost,
        corporationId: location.corporationId.toString(),
        restockedBy: characterId
      });

      res.json(successResponse(
        {
          restocked: {
            itemId,
            quantityAdded: quantity,
            newStock: item.currentStock,
            costPaid: restockCost,
            paidFrom: payFromTreasury ? 'treasury' : 'personal'
          },
          treasury: {
            previousBalance: ((treasuryValue as any) || 0) + restockCost,
            newBalance: (treasuryValue as any) || 0
          }
        },
        undefined,
        getRequestId(req)
      ));

    } catch (error: unknown) {
      const err = error as Error;
      logger.error('Restock shop error:', {
        error: err.message,
        stack: err.stack,
        name: err.name,
        characterId: req.character?.characterId,
        shopId: req.params?.shopId,
        requestBody: req.body,
        params: req.params
      });

      res.status(500).json(errorResponse(
        'Impossibile rifornire il negozio',
        'RESTOCK_ERROR',
        undefined,
        500,
        getRequestId(req)
      ));
    }
  }

  // Helper Methods

  private static formatCurrency(pence: number): string {
    return `${pence} penny`;
  }

  // Bug preesistente preservato esattamente, trovato in test E2E su Docker
  // (Fase 6.4): legge location.private/location.visible al livello sbagliato
  // — lo schema reale li annida sotto location.settings.private/.visible
  // (vedi database/models/Location.ts) — entrambi sempre undefined qui,
  // quindi questo metodo restituisce sempre false per qualunque location
  // reale. Di conseguenza getShopItems risponde sempre 404
  // INVALID_LOCATION_ACCESS per qualunque location diversa da "london":
  // il negozio generale (getGeneralStore/purchaseItem) è l'unico percorso
  // shop di fatto funzionante oggi. Comportamento identico a prima dello
  // spostamento in features/oggetti (stesso codice verbatim).
  private static async checkLocationAccess(location: any, character: any): Promise<boolean> {
    if (!location.private && location.visible) return true;

    if (location.private) {
      if (location.ownerId?.toString() === character.id) return true;

      if (location.corporationId && character.corporations) {
        const isMember = character.corporations.some(
          (corp: any) => corp.id.toString() === location.corporationId.toString()
        );
        if (isMember) return true;
      }
    }

    return false;
  }

  private static canPurchaseItem(shopItem: any, character: any): boolean {
    // Get the actual item data from the populated itemId
    const item = shopItem.itemId;

    // Must have item data populated
    if (!item) return false;

    // Must be public (visible to all) or available in location
    if (!item.isPublic && (!item.availableLocations || item.availableLocations.length === 0)) return false;

    // Must be in stock
    if (shopItem.currentStock <= 0) return false;

    // Check requirements on the actual item
    return ShopController.meetsRequirements(item, character);
  }

  /**
   * Read a character's skill value, handling both Map (Mongoose document)
   * and plain-object (post-.lean()) shapes, plus granular SkillBreakdown
   * objects ({ total, base, ... }) vs plain numbers.
   */
  private static getCharacterSkillValue(character: any, skillKey: string): number {
    const skills = character.skills;
    if (!skills) return 0;
    const raw = skills instanceof Map ? skills.get(skillKey) : skills[skillKey];
    if (typeof raw === 'object' && raw !== null && 'total' in raw) {
      return raw.total || 0;
    }
    return typeof raw === 'number' ? raw : 0;
  }

  // Bug preesistente preservato esattamente: item.requirements.corporations è
  // {corporationId, minimumRole?}[] (vedi models/Item.ts, IItem.prerequisites.
  // requiredCorporations), ma reqCorp.toString() produce sempre "[object Object]"
  // invece di reqCorp.corporationId.toString() — nessun item con
  // requiredCorporations è mai acquistabile da nessuno, nemmeno dai membri
  // della corporazione richiesta.
  private static meetsRequirements(item: any, character: any): boolean {
    if (!item.requirements) return true;

    // Check skill requirements — item.requirements.skills is keyed by skillId
    // (Item.prerequisites.minimumSkills, a Map<string, number> in the schema —
    // a plain object after .lean(), a real Map otherwise), not an array.
    if (item.requirements.skills) {
      const skillEntries: [string, number][] = item.requirements.skills instanceof Map
        ? Array.from(item.requirements.skills.entries())
        : Object.entries(item.requirements.skills);

      for (const [skillKey, minimum] of skillEntries) {
        const characterSkill = ShopController.getCharacterSkillValue(character, skillKey);
        if (characterSkill < minimum) {
          return false;
        }
      }
    }

    // Check occupation requirements
    if (item.requirements.occupations && item.requirements.occupations.length > 0) {
      if (!item.requirements.occupations.includes(character.occupation)) {
        return false;
      }
    }

    // Check corporation requirements
    if (item.requirements.corporations && item.requirements.corporations.length > 0) {
      const characterCorps = character.corporations?.map((c: any) => c.id.toString()) || [];
      const hasRequiredCorp = item.requirements.corporations.some(
        (reqCorp: any) => characterCorps.includes(reqCorp.toString())
      );
      if (!hasRequiredCorp) return false;
    }

    return true;
  }

}
