import mongoose, { Schema, model, Document, QueryFilter } from 'mongoose';
import { softDeletePlugin, SoftDeleteMethods } from '../plugins/softDeletePlugin';

export interface ILocationPosition {
  name: string;
  image?: string;
  description?: string;
}

export interface ILocation extends Document, SoftDeleteMethods {
  // Basic info
  name: string;
  slug: string;
  description: string;
  district: string;
  parentLocation?: Schema.Types.ObjectId;
  imageUrl?: string; // URL CDN (upload manuale via pannello gestione)
  image?: string;    // Filename statico in apps/game/public/artifacts/locations/ (es. "london.png"),
                      // generato da local-tools/imagegen — stesso pattern di Item.image
  descriptionImages: string[]; // URL immagini mostrate accanto alla descrizione nel popup info location

  // Location settings (control switches)
  settings: {
    visible: boolean;    // Location appears in navigation
    chat: boolean;       // Chat functionality available
    shop: boolean;       // Commerce/trading functionality
    private: boolean;    // Access control system activated
  };
  
  // Hierarchy and positioning
  locationLevel: 'root' | 'district' | 'location';
  sortOrder: number;
  
  // Private location access control
  access?: {
    ownerId?: Schema.Types.ObjectId;  // Character who owns this location
    ownerType?: 'character' | 'corporation';
    
    // Character-specific access grants
    characterAccess: {
      characterId: Schema.Types.ObjectId;
      permissions: ('view' | 'chat' | 'manage')[];
      grantedBy: Schema.Types.ObjectId;
      grantedAt: Date;
      duration: 'permanent' | 'temporary';
      expiresAt?: Date;
    }[];
    
    // Corporation access (members of these corporations can access)
    corporationAccess: {
      corporationId: Schema.Types.ObjectId;
      permissions: ('view' | 'chat' | 'manage')[];
      minimumRole?: string;
    }[];
  };

  // Lightweight name+avatar personas scoped to this location, used to override
  // the poster's displayed name/avatar (e.g. "il barista", "il maggiordomo").
  // Usable by the location owner and by master. Distinct from `npcs` (full
  // Character-backed PNGs) and from Character.fakePngs (per-character masking).
  locationPngs?: {
    name: string;
    surname?: string;
    avatar?: string;
    createdAt: Date;
    createdBy: Schema.Types.ObjectId;
  }[];

  // Location limits and rules
  maxOccupants?: number;
  accessRules?: {
    requiredLevel?: number;
    bannedCharacters?: Schema.Types.ObjectId[];
    allowedCorporations?: Schema.Types.ObjectId[];
    timeRestrictions?: {
      openTime?: string;
      closeTime?: string;
      allowedDays?: number[];
    };
  };
  
  // Active Gaming Session Management
  // Auto-created session when chat activity starts, expires after 3 hours of inactivity
  activeSession?: {
    sessionId: Schema.Types.ObjectId;  // Reference to GamingSession document
    startedAt: Date;                   // When the session was auto-created
    lastActivityAt: Date;              // Last message timestamp (for TTL)
    expiresAt: Date;                   // When session will auto-finalize (3 hours from last activity)
    isAutoGenerated: boolean;          // True if auto-created, false if master-created
    participantIds: Schema.Types.ObjectId[]; // Characters who participated (for quick lookup)
  };

  // Current occupants (real-time presence tracking)
  occupants: {
    characterId: Schema.Types.ObjectId;
    characterName: string;
    enteredAt: Date;
    lastSeen: Date;
    isActive: boolean; // true if character is currently online
    currentTag?: string; // Current position tag (e.g., "Tavolo", "Bancone del Bar")
  }[];

  // NPCs in this location
  npcs: {
    npcId: Schema.Types.ObjectId;
    isActive: boolean;
    activationPriority: number;
    contextualRelevance: number;
  }[];

  // Bot AI integration
  bot_enabled: boolean; // true = bot interaction enabled for this location
  botCharacterId?: Schema.Types.ObjectId; // Character ID of the bot assigned to this location

  // Bot round tracking — collects all player actions before notifying the bot
  botRound?: {
    roundNumber: number;
    actedCharacterIds: Schema.Types.ObjectId[];
    roundActionIds: Schema.Types.ObjectId[];
    startedAt: Date;
  };

  // Location statistics (updated periodically)
  statistics: {
    totalVisits: number;
    uniqueVisitors: number;
    averageStayTime: number; // in minutes
    messagesExchanged: number;
    lastActivityAt?: Date;
    peakHours: string[];
  };

  // Physical positions/sub-locations (e.g., "Tavolo 1", "Bancone", "Angolo Nord")
  // Used in chat to indicate where character is within the location
  positions?: ILocationPosition[];

  // Management info
  createdBy: Schema.Types.ObjectId;
  lastModifiedBy?: Schema.Types.ObjectId;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

const LocationSchema = new Schema<ILocation>({
  // Basic info
  name: {
    type: String,
    required: true,
    trim: true,
    maxlength: 100
  },
  slug: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    maxlength: 100,
    lowercase: true,
    index: true
  },
  description: {
    type: String,
    required: true,
    trim: true,
    maxlength: 2000
  },
  district: {
    type: String,
    required: true,
    trim: true
  },
  parentLocation: {
    type: Schema.Types.ObjectId,
    ref: 'Location'
  },
  imageUrl: {
    type: String,
    trim: true,
    maxlength: 500
  },
  image: {
    type: String,
    trim: true,
    maxlength: 255
  },
  descriptionImages: {
    type: [{ type: String, trim: true, maxlength: 500 }],
    default: []
  },

  // Location settings
  settings: {
    visible: { type: Boolean, default: true },
    chat: { type: Boolean, default: true },
    shop: { type: Boolean, default: false },
    private: { type: Boolean, default: false }
  },
  
  // Hierarchy
  locationLevel: {
    type: String,
    required: true,
    enum: ['root', 'district', 'location']
  },
  sortOrder: {
    type: Number,
    default: 0
  },
  
  // Access control
  access: {
    ownerId: {
      type: Schema.Types.ObjectId,
      refPath: 'access.ownerType'
    },
    ownerType: {
      type: String,
      enum: ['character', 'corporation']
    },
    
    characterAccess: [{
      characterId: {
        type: Schema.Types.ObjectId,
        ref: 'Character',
        required: true
      },
      permissions: [{
        type: String,
        enum: ['view', 'chat', 'manage']
      }],
      grantedBy: {
        type: Schema.Types.ObjectId,
        ref: 'Character',
        required: true
      },
      grantedAt: {
        type: Date,
        required: true
      },
      duration: {
        type: String,
        enum: ['permanent', 'temporary'],
        default: 'permanent'
      },
      expiresAt: Date
    }],
    
    corporationAccess: [{
      corporationId: {
        type: Schema.Types.ObjectId,
        ref: 'Corporation',
        required: true
      },
      permissions: [{
        type: String,
        enum: ['view', 'chat', 'manage']
      }],
      minimumRole: String
    }]
  },

  // Location-scoped PNG personas (see ILocation.locationPngs)
  locationPngs: {
    type: [{
      name: {
        type: String,
        required: true,
        trim: true,
        minlength: 2,
        maxlength: 50
      },
      surname: {
        type: String,
        trim: true,
        maxlength: 50
      },
      avatar: {
        type: String,
        trim: true,
        maxlength: 500
      },
      createdAt: {
        type: Date,
        default: Date.now
      },
      createdBy: {
        type: Schema.Types.ObjectId,
        ref: 'Character',
        required: true
      }
    }],
    default: [],
    validate: {
      validator: function(v: any[]) {
        return !v || v.length <= 20;
      },
      message: 'Maximum 20 location PNGs allowed per location'
    }
  },

  // Location rules
  maxOccupants: {
    type: Number,
    min: 1,
    max: 100
  },
  accessRules: {
    requiredLevel: {
      type: Number,
      min: 1
    },
    bannedCharacters: [{
      type: Schema.Types.ObjectId,
      ref: 'Character'
    }],
    allowedCorporations: [{
      type: Schema.Types.ObjectId,
      ref: 'Corporation'
    }],
    timeRestrictions: {
      openTime: String,
      closeTime: String,
      allowedDays: [Number] // 0-6 (Sunday to Saturday)
    }
  },
  
  // Active Gaming Session Management
  activeSession: {
    sessionId: {
      type: Schema.Types.ObjectId,
      ref: 'GamingSession'
    },
    startedAt: Date,
    lastActivityAt: Date,
    expiresAt: {
      type: Date,
      index: true // Index for TTL cleanup queries
    },
    isAutoGenerated: {
      type: Boolean,
      default: true
    },
    participantIds: [{
      type: Schema.Types.ObjectId,
      ref: 'Character'
    }]
  },

  // Current occupants
  occupants: [{
    characterId: {
      type: Schema.Types.ObjectId,
      ref: 'Character',
      required: true
    },
    characterName: {
      type: String,
      required: true,
      trim: true
    },
    enteredAt: {
      type: Date,
      required: true,
      default: Date.now
    },
    lastSeen: {
      type: Date,
      required: true,
      default: Date.now
    },
    isActive: {
      type: Boolean,
      default: true
    },
    currentTag: {
      type: String,
      trim: true,
      maxlength: 50
    }
  }],

  // NPCs
  npcs: [{
    npcId: {
      type: Schema.Types.ObjectId,
      ref: 'NPC',
      required: true
    },
    isActive: {
      type: Boolean,
      default: true
    },
    activationPriority: {
      type: Number,
      default: 1,
      min: 1,
      max: 10
    },
    contextualRelevance: {
      type: Number,
      default: 0.5,
      min: 0,
      max: 1
    }
  }],

  // Bot AI integration
  bot_enabled: {
    type: Boolean,
    default: false
  },
  botCharacterId: {
    type: Schema.Types.ObjectId,
    ref: 'Character'
  },

  // Bot round tracking
  botRound: {
    roundNumber: { type: Number, default: 0 },
    actedCharacterIds: [{ type: Schema.Types.ObjectId, ref: 'Character' }],
    roundActionIds: [{ type: Schema.Types.ObjectId, ref: 'Chat' }],
    startedAt: { type: Date }
  },

  // Statistics
  statistics: {
    totalVisits: { type: Number, default: 0 },
    uniqueVisitors: { type: Number, default: 0 },
    averageStayTime: { type: Number, default: 0 },
    messagesExchanged: { type: Number, default: 0 },
    lastActivityAt: Date,
    peakHours: [String]
  },

  // Physical positions within location (e.g., "Tavolo 1", "Bancone")
  positions: {
    type: [{
      name: { type: String, required: true, trim: true, maxlength: 50 },
      image: { type: String, trim: true, maxlength: 500 },
      description: { type: String, trim: true, maxlength: 500 }
    }],
    default: []
  },

  // Management
  createdBy: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  lastModifiedBy: {
    type: Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true,
  collection: 'locations'
});

// Indexes
LocationSchema.index({ name: 1 });
LocationSchema.index({ district: 1 });
LocationSchema.index({ parentLocation: 1 });
LocationSchema.index({ locationLevel: 1, sortOrder: 1 });
LocationSchema.index({ 'settings.visible': 1, 'settings.private': 1 });
LocationSchema.index({ 'access.ownerId': 1 });
LocationSchema.index({ 'access.characterAccess.characterId': 1 });
LocationSchema.index({ 'access.corporationAccess.corporationId': 1 });
LocationSchema.index({ 'occupants.characterId': 1 });
LocationSchema.index({ 'occupants.isActive': 1 });

// Methods
LocationSchema.methods.canCharacterAccess = function(characterId: Schema.Types.ObjectId, requiredPermission = 'view') {
  // Public locations are always accessible (if visible)
  if (!this.settings.private) {
    return this.settings.visible;
  }
  
  // Check if character is owner
  if (this.access?.ownerType === 'character' && this.access?.ownerId?.equals(characterId)) {
    return true;
  }
  
  // Check character-specific access
  if (this.access?.characterAccess) {
    const access = this.access.characterAccess.find((a: any) => a.characterId.equals(characterId));
    if (access) {
      // Check if access is expired
      if (access.duration === 'temporary' && access.expiresAt && new Date() > access.expiresAt) {
        return false;
      }
      return access.permissions.includes(requiredPermission);
    }
  }
  
  return false;
};

LocationSchema.methods.canCorporationAccess = function(corporationId: Schema.Types.ObjectId, memberRole?: string) {
  if (!this.settings.private) {
    return this.settings.visible;
  }
  
  // Check if corporation owns the location
  if (this.access?.ownerType === 'corporation' && this.access?.ownerId?.equals(corporationId)) {
    return true;
  }
  
  // Check corporation access rules
  if (this.access?.corporationAccess) {
    const access = this.access.corporationAccess.find((a: any) => a.corporationId.equals(corporationId));
    if (access) {
      // Check minimum role requirement
      if (access.minimumRole && memberRole) {
        // Role hierarchy check would go here
        return true; // Simplified for now
      }
      return true;
    }
  }
  
  return false;
};

LocationSchema.methods.grantCharacterAccess = function(characterId: Schema.Types.ObjectId, permissions: string[], grantedBy: Schema.Types.ObjectId, duration = 'permanent', expiresAt?: Date) {
  if (!this.access) {
    this.access = { characterAccess: [], corporationAccess: [] };
  }
  
  // Remove existing access for this character
  this.access.characterAccess = this.access.characterAccess.filter((a: any) => !a.characterId.equals(characterId));
  
  // Add new access
  this.access.characterAccess.push({
    characterId,
    permissions,
    grantedBy,
    grantedAt: new Date(),
    duration,
    expiresAt
  });
};

LocationSchema.methods.revokeCharacterAccess = function(characterId: Schema.Types.ObjectId) {
  if (this.access?.characterAccess) {
    this.access.characterAccess = this.access.characterAccess.filter((a: any) => !a.characterId.equals(characterId));
  }
};

LocationSchema.methods.updateStatistics = function(updateData: Partial<ILocation['statistics']>) {
  Object.assign(this.statistics, updateData);
  this.statistics.lastActivityAt = new Date();
};

LocationSchema.methods.addNPC = function(npcId: Schema.Types.ObjectId, priority = 1, relevance = 0.5) {
  // Remove existing NPC entry
  this.npcs = this.npcs.filter((n: any) => !n.npcId.equals(npcId));
  
  // Add new entry
  this.npcs.push({
    npcId,
    isActive: true,
    activationPriority: priority,
    contextualRelevance: relevance
  });
};

LocationSchema.methods.getActiveNPCs = function() {
  return this.npcs.filter((n: any) => n.isActive).sort((a: any, b: any) => b.activationPriority - a.activationPriority);
};

// Occupant management methods
LocationSchema.methods.addOccupant = async function(characterId: Schema.Types.ObjectId, characterName: string, currentTag?: string) {
  const now = new Date();

  // Use atomic update to avoid full document validation
  // First, remove any existing occupant with same characterId
  await mongoose.model<ILocation>('Location').updateOne(
    { _id: this._id },
    { $pull: { occupants: { characterId } } }
  );

  // Then add new occupant entry
  return mongoose.model<ILocation>('Location').updateOne(
    { _id: this._id },
    {
      $push: {
        occupants: {
          characterId,
          characterName,
          enteredAt: now,
          lastSeen: now,
          isActive: true,
          currentTag: currentTag || undefined
        }
      }
    }
  );
};

LocationSchema.methods.removeOccupant = async function(characterId: Schema.Types.ObjectId) {
  // Use atomic update to avoid full document validation
  return mongoose.model<ILocation>('Location').updateOne(
    { _id: this._id },
    { $pull: { occupants: { characterId } } }
  );
};

LocationSchema.methods.updateOccupantLastSeen = async function(characterId: Schema.Types.ObjectId) {
  const now = new Date();

  // Use atomic update to avoid full document validation
  // Update only the matching occupant's lastSeen and isActive fields
  return mongoose.model<ILocation>('Location').updateOne(
    { _id: this._id, 'occupants.characterId': characterId },
    {
      $set: {
        'occupants.$.lastSeen': now,
        'occupants.$.isActive': true
      }
    }
  );
};

LocationSchema.methods.updateOccupantTag = async function(characterId: Schema.Types.ObjectId, currentTag?: string) {
  const now = new Date();

  // Use atomic update to avoid full document validation
  return mongoose.model<ILocation>('Location').updateOne(
    { _id: this._id, 'occupants.characterId': characterId },
    {
      $set: {
        'occupants.$.currentTag': currentTag,
        'occupants.$.lastSeen': now,
        'occupants.$.isActive': true
      }
    }
  );
};

LocationSchema.methods.getActiveOccupants = function() {
  return this.occupants.filter((o: any) => o.isActive);
};

LocationSchema.methods.markOccupantInactive = async function(characterId: Schema.Types.ObjectId) {
  // Use atomic update to avoid full document validation
  return mongoose.model<ILocation>('Location').updateOne(
    { _id: this._id, 'occupants.characterId': characterId },
    {
      $set: {
        'occupants.$.isActive': false
      }
    }
  );
};

// Session management methods
LocationSchema.methods.getOrCreateSession = async function(characterId: Schema.Types.ObjectId, characterName: string) {
  const now = new Date();
  const SESSION_TTL_HOURS = 3;

  // Check if there's an active session that hasn't expired
  if (this.activeSession && this.activeSession.expiresAt > now) {
    // Refresh the TTL
    this.activeSession.lastActivityAt = now;
    this.activeSession.expiresAt = new Date(now.getTime() + SESSION_TTL_HOURS * 60 * 60 * 1000);

    // Add character to participants if not already there
    if (!this.activeSession.participantIds.some((id: any) => id.equals(characterId))) {
      this.activeSession.participantIds.push(characterId);

      // Also update GamingSession participants
      const GamingSession = mongoose.model('GamingSession');
      await GamingSession.findByIdAndUpdate(this.activeSession.sessionId, {
        $addToSet: {
          participants: {
            characterId,
            characterName,
            joinedAt: now,
            wasActive: true,
            participationScore: 5
          }
        }
      });
    }

    return this.activeSession.sessionId;
  }

  // Create new auto-generated gaming session
  const GamingSession = mongoose.model('GamingSession');
  const newSession = await GamingSession.create({
    title: `Auto-Session at ${this.name}`,
    description: `Automatically generated session from chat activity`,
    masterId: characterId, // First participant becomes temporary master
    masterName: characterName,
    sessionDate: now,
    startTime: now,
    estimatedDuration: 180, // 3 hours default
    primaryLocation: this._id,
    sessionType: 'social',
    difficultyLevel: 'medium',
    participants: [{
      characterId,
      characterName,
      joinedAt: now,
      wasActive: true,
      participationScore: 5
    }],
    status: 'active',
    experienceAssigned: false
  });

  this.activeSession = {
    sessionId: newSession._id,
    startedAt: now,
    lastActivityAt: now,
    expiresAt: new Date(now.getTime() + SESSION_TTL_HOURS * 60 * 60 * 1000),
    isAutoGenerated: true,
    participantIds: [characterId]
  };

  return newSession._id;
};

LocationSchema.methods.refreshSessionTTL = async function(characterId?: Schema.Types.ObjectId, characterName?: string) {
  const now = new Date();
  const SESSION_TTL_HOURS = 3;

  if (this.activeSession) {
    this.activeSession.lastActivityAt = now;
    this.activeSession.expiresAt = new Date(now.getTime() + SESSION_TTL_HOURS * 60 * 60 * 1000);

    // Add character to participants if provided and not already there
    if (characterId && !this.activeSession.participantIds.some((id: any) => id.equals(characterId))) {
      this.activeSession.participantIds.push(characterId);

      // Also update GamingSession participants
      if (characterName) {
        const GamingSession = mongoose.model('GamingSession');
        await GamingSession.findByIdAndUpdate(this.activeSession.sessionId, {
          $addToSet: {
            participants: {
              characterId,
              characterName,
              joinedAt: now,
              wasActive: true,
              participationScore: 5
            }
          }
        });
      }
    }
  }
};

LocationSchema.methods.finalizeAutoSession = async function() {
  if (!this.activeSession || !this.activeSession.isAutoGenerated) {
    return;
  }

  const now = new Date();
  const GamingSession = mongoose.model('GamingSession');

  // Update session with final data
  await GamingSession.findByIdAndUpdate(this.activeSession.sessionId, {
    endTime: now,
    status: 'completed',
    totalActiveTime: Math.round((now.getTime() - this.activeSession.startedAt.getTime()) / 60000) // minutes
  });

  // Clear active session from location
  this.activeSession = undefined;
  return this.save();
};

LocationSchema.methods.isSessionActive = function() {
  if (!this.activeSession) return false;
  return this.activeSession.expiresAt > new Date();
};

// Static methods
LocationSchema.statics.findAccessibleByCharacter = function(characterId: Schema.Types.ObjectId, corporationIds: Schema.Types.ObjectId[] = []) {
  const query: QueryFilter<ILocation> = {
    $or: [
      // Public locations
      { 'settings.visible': true, 'settings.private': false },
      // Character owns the location
      { 'access.ownerType': 'character', 'access.ownerId': characterId },
      // Character has specific access
      { 'access.characterAccess.characterId': characterId },
      // Character's corporations have access
      ...(corporationIds.length > 0 ? [
        { 'access.ownerType': 'corporation' as const, 'access.ownerId': { $in: corporationIds } },
        { 'access.corporationAccess.corporationId': { $in: corporationIds } }
      ] : [])
    ]
  };
  return this.find(query);
};

// Apply soft delete plugin
LocationSchema.plugin(softDeletePlugin, {
  uniqueKeys: ['slug'],
  deletedByField: 'Character'
});

export const Location = mongoose.models.Location || model<ILocation>('Location', LocationSchema);