/**
 * System Configuration Seeder
 *
 * Seeds all SystemConfiguration records:
 * - character_creation: Game settings (approval, max chars, etc.)
 * - economy: Starting cash, salary, inflation
 * - moderation: Chat moderation, reports, appeals
 * - postal_system: Message length, edit time, delivery
 * - combat_system: Damage bonus table, unarmed damage, success labels
 * - system: Maintenance mode
 *
 * Uses upsert-skip logic: existing records are never overwritten.
 */

import { getConnection } from '../utils/connection.js';

const COLLECTION = 'system_configurations';

interface ConfigRecord {
  configKey: string;
  configSection: string;
  configType: 'boolean' | 'number' | 'string' | 'json';
  value: any;
  defaultValue: any;
  description: string;
  isActive: boolean;
  metadata: { version: number };
}

const ALL_CONFIGS: ConfigRecord[] = [
  // ── character_creation ──────────────────────────────────────────
  {
    configKey: 'max_characters_per_user',
    configSection: 'character_creation',
    configType: 'number',
    value: 3,
    defaultValue: 3,
    description: 'Numero massimo di personaggi per utente',
    isActive: true,
    metadata: { version: 1 },
  },

  // Stats Section (9 records)
  {
    configKey: 'character_creation_stats_base_points',
    configSection: 'character_creation',
    configType: 'number',
    value: 20,
    defaultValue: 20,
    description: 'Punti base per ogni statistica prima della distribuzione',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_stats_total_points',
    configSection: 'character_creation',
    configType: 'number',
    value: 400,
    defaultValue: 400,
    description: 'Totale punti da distribuire nelle caratteristiche (wizard Step 3)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_stats_max_above_80',
    configSection: 'character_creation',
    configType: 'number',
    value: 2,
    defaultValue: 2,
    description: 'Numero massimo di statistiche che possono superare 80 durante creazione',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_stats_creation_cap',
    configSection: 'character_creation',
    configType: 'number',
    value: 85,
    defaultValue: 85,
    description: 'Cap massimo per statistica durante wizard creazione (DRAFT)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_stats_gameplay_cap',
    configSection: 'character_creation',
    configType: 'number',
    value: 99,
    defaultValue: 99,
    description: 'Cap massimo per statistica durante gameplay (APPROVED)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_stats_min_values',
    configSection: 'character_creation',
    configType: 'json',
    value: {
      strength: 20,
      dexterity: 20,
      intelligence: 20,
      constitution: 20,
      size: 20,
      charm: 20,
      power: 20,
      education: 20,
    },
    defaultValue: {
      strength: 20,
      dexterity: 20,
      intelligence: 20,
      constitution: 20,
      size: 20,
      charm: 20,
      power: 20,
      education: 20,
    },
    description: 'Valori minimi per ogni statistica (oggetto chiave-valore)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_stats_description',
    configSection: 'character_creation',
    configType: 'string',
    value: 'Caratteristiche primarie: 20 base + 400 punti da distribuire. Limite creazione 85, gameplay 99.',
    defaultValue: '',
    description: 'Descrizione del sistema stats per admin UI',
    isActive: true,
    metadata: { version: 1 },
  },

  // Skills Section (7 records)
  {
    configKey: 'character_creation_skills_total_points_formula',
    configSection: 'character_creation',
    configType: 'string',
    value: 'constant:200',
    defaultValue: 'constant:200',
    description: 'Formula per calcolare punti abilità base (constant:N o formula:EDUx4)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_skills_int_bonus_formula',
    configSection: 'character_creation',
    configType: 'string',
    value: 'INT/2',
    defaultValue: 'INT/2',
    description: 'Formula bonus intelligenza (INT/2, INTx2, INT+10, constant:N)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_skills_creation_cap',
    configSection: 'character_creation',
    configType: 'number',
    value: 75,
    defaultValue: 75,
    description: 'Cap massimo per abilità normale durante creazione (wizard Step 4)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_skills_creation_cap_with_occupation',
    configSection: 'character_creation',
    configType: 'number',
    value: 80,
    defaultValue: 80,
    description: 'Cap massimo per abilità con bonus occupazione durante creazione',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_skills_gameplay_cap',
    configSection: 'character_creation',
    configType: 'number',
    value: 99,
    defaultValue: 99,
    description: 'Cap massimo per abilità durante gameplay',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_skills_physical_exclude_int_bonus',
    configSection: 'character_creation',
    configType: 'boolean',
    value: true,
    defaultValue: true,
    description: 'Le abilità fisiche escludono bonus INT',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_skills_description',
    configSection: 'character_creation',
    configType: 'string',
    value: 'Abilità: 200 base + bonus INT configurabile. Cap creazione 75 (80 con occupazione), gameplay 99. Abilità fisiche escludono bonus INT.',
    defaultValue: '',
    description: 'Descrizione del sistema skills per admin UI',
    isActive: true,
    metadata: { version: 1 },
  },

  // Occupation Section (5 records)
  {
    configKey: 'character_creation_occupation_required_skill_minimum',
    configSection: 'character_creation',
    configType: 'number',
    value: 40,
    defaultValue: 40,
    description: 'Valore minimo richiesto per abilità obbligatorie occupazione',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_occupation_bonus_skill_points',
    configSection: 'character_creation',
    configType: 'number',
    value: 30,
    defaultValue: 30,
    description: 'Punti bonus per abilità scelta (1 abilità bonus)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_occupation_required_skill_count',
    configSection: 'character_creation',
    configType: 'json',
    value: { min: 6, max: 6 },
    defaultValue: { min: 6, max: 6 },
    description: 'Range numero abilità obbligatorie per occupazione',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_occupation_bonus_skill_count',
    configSection: 'character_creation',
    configType: 'json',
    value: { min: 1, max: 1 },
    defaultValue: { min: 1, max: 1 },
    description: 'Range numero abilità bonus selezionabili',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_occupation_description',
    configSection: 'character_creation',
    configType: 'string',
    value: 'Occupazioni: 6 abilità obbligatorie (min 40), 1 abilità bonus (+30 punti gratuiti)',
    defaultValue: '',
    description: 'Descrizione del sistema occupazioni per admin UI',
    isActive: true,
    metadata: { version: 1 },
  },

  // Limits Section (4 records)
  {
    configKey: 'character_creation_limits_age',
    configSection: 'character_creation',
    configType: 'json',
    value: { min: 16, max: 80 },
    defaultValue: { min: 16, max: 80 },
    description: 'Range età personaggio (anni)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_limits_weight',
    configSection: 'character_creation',
    configType: 'json',
    value: { min: 30, max: 200, unit: 'kg' },
    defaultValue: { min: 30, max: 200, unit: 'kg' },
    description: 'Range peso personaggio',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_limits_height',
    configSection: 'character_creation',
    configType: 'json',
    value: { min: 100, max: 250, unit: 'cm' },
    defaultValue: { min: 100, max: 250, unit: 'cm' },
    description: 'Range altezza personaggio',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_limits_background_fields',
    configSection: 'character_creation',
    configType: 'json',
    value: {
      briefHistoryMin: 100,
      personalityMin: 50,
      goalsMin: 50,
      maxLength: 4000,
    },
    defaultValue: {
      briefHistoryMin: 100,
      personalityMin: 50,
      goalsMin: 50,
      maxLength: 4000,
    },
    description: 'Limiti lunghezza campi background (caratteri)',
    isActive: true,
    metadata: { version: 1 },
  },

  // Social Classes (1 JSON array record)
  {
    configKey: 'character_creation_social_classes',
    configSection: 'character_creation',
    configType: 'json',
    value: [
      { id: 'destitute', name: 'Indigente', financeSkillRange: { min: 1, max: 9 }, weeklyCredit: 2, initialWealth: { minCash: 5, maxCash: 15 } },
      { id: 'poor', name: 'Povero', financeSkillRange: { min: 10, max: 19 }, weeklyCredit: 5, initialWealth: { minCash: 20, maxCash: 40 } },
      { id: 'modest', name: 'Modesto', financeSkillRange: { min: 20, max: 39 }, weeklyCredit: 15, initialWealth: { minCash: 50, maxCash: 100 } },
      { id: 'lower_middle', name: 'Piccola borghesia', financeSkillRange: { min: 40, max: 49 }, weeklyCredit: 30, initialWealth: { minCash: 150, maxCash: 300 } },
      { id: 'middle_class', name: 'Media borghesia', financeSkillRange: { min: 50, max: 69 }, weeklyCredit: 75, initialWealth: { minCash: 400, maxCash: 800 } },
      { id: 'wealthy', name: 'Ricco', financeSkillRange: { min: 70, max: 79 }, weeklyCredit: 150, initialWealth: { minCash: 1000, maxCash: 2000 } },
      { id: 'affluent', name: 'Facoltoso', financeSkillRange: { min: 80, max: 89 }, weeklyCredit: 300, initialWealth: { minCash: 3000, maxCash: 5000 } },
      { id: 'elite', name: 'Élite', financeSkillRange: { min: 90, max: 99 }, weeklyCredit: 500, initialWealth: { minCash: 8000, maxCash: 15000 } },
    ],
    defaultValue: [],
    description: '8 classi sociali basate su skill FINANZA',
    isActive: true,
    metadata: { version: 1 },
  },

  // Formulas Section (2 JSON records)
  {
    configKey: 'character_creation_formulas_derived',
    configSection: 'character_creation',
    configType: 'json',
    value: {
      hitPoints: 'FLOOR((CON + SIZ) / 10)',
      sanityPoints: 'POW',
      magicPoints: 'FLOOR(POW / 5)',
      luck: 'POW',
      ideaRoll: 'INT',
      knowledge: 'EDU',
      movementRate: '8',
    },
    defaultValue: {},
    description: 'Formule per calcolo statistiche derivate (supportano FLOOR, CEIL, ROUND, +, -, *, /)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'character_creation_formulas_damage_bonus',
    configSection: 'character_creation',
    configType: 'json',
    value: [
      { maxTotal: 64, bonus: '-2', build: -2 },
      { maxTotal: 84, bonus: '-1', build: -1 },
      { maxTotal: 124, bonus: '0', build: 0 },
      { maxTotal: 164, bonus: '+1d4', build: 1 },
      { maxTotal: 204, bonus: '+1d6', build: 2 },
      { maxTotal: 284, bonus: '+2d6', build: 3 },
      { maxTotal: 364, bonus: '+3d6', build: 4 },
      { maxTotal: 444, bonus: '+4d6', build: 5 },
      { maxTotal: 9999, bonus: '+5d6', build: 6 },
    ],
    defaultValue: [],
    description: 'Tabella bonus danno basato su STR + SIZ',
    isActive: true,
    metadata: { version: 1 },
  },

  // Metadata (1 JSON record)
  {
    configKey: 'character_creation_meta',
    configSection: 'character_creation',
    configType: 'json',
    value: {
      version: '1.0.0',
      description: 'TenPennyNovels - Call of Cthulhu Victorian RPG Character Creation Configuration',
      lastUpdated: '2025-01-15T00:00:00.000Z',
      lastModifiedBy: 'system',
    },
    defaultValue: {},
    description: 'Metadata configurazione character creation',
    isActive: true,
    metadata: { version: 1 },
  },

  // ── economy ─────────────────────────────────────────────────────
  {
    configKey: 'starting_cash',
    configSection: 'economy',
    configType: 'number',
    value: 50,
    defaultValue: 50,
    description: 'Contanti iniziali per un nuovo personaggio (£)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'starting_deposit',
    configSection: 'economy',
    configType: 'number',
    value: 200,
    defaultValue: 200,
    description: 'Deposito bancario iniziale per un nuovo personaggio (£)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'daily_salary_enabled',
    configSection: 'economy',
    configType: 'boolean',
    value: true,
    defaultValue: true,
    description: 'Abilita il salario giornaliero automatico',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'inflation_rate',
    configSection: 'economy',
    configType: 'number',
    value: 0.02,
    defaultValue: 0.02,
    description: 'Tasso di inflazione applicato ai prezzi (0.02 = 2%)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'taxation_enabled',
    configSection: 'economy',
    configType: 'boolean',
    value: false,
    defaultValue: false,
    description: 'Abilita il sistema di tassazione',
    isActive: true,
    metadata: { version: 1 },
  },

  // ── moderation ──────────────────────────────────────────────────
  {
    configKey: 'report_system_enabled',
    configSection: 'moderation',
    configType: 'boolean',
    value: true,
    defaultValue: true,
    description: 'Abilita il sistema di segnalazioni utente',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'ai_moderation_enabled',
    configSection: 'moderation',
    configType: 'boolean',
    value: false,
    defaultValue: false,
    description: 'Abilita la moderazione automatica AI dei messaggi chat (distilbert-multilingual-toxicity-classifier)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'ai_moderation_threshold',
    configSection: 'moderation',
    configType: 'number',
    value: 0.7,
    defaultValue: 0.7,
    description: 'Soglia di tossicità (0.0–1.0) oltre la quale un messaggio viene flaggato automaticamente',
    isActive: true,
    metadata: { version: 1 },
  },

  // ── postal_system ───────────────────────────────────────────────
  {
    configKey: 'max_message_length',
    configSection: 'postal_system',
    configType: 'number',
    value: 2000,
    defaultValue: 2000,
    description: 'Lunghezza massima dei messaggi postali (caratteri)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'message_edit_time_limit',
    configSection: 'postal_system',
    configType: 'number',
    value: 300,
    defaultValue: 300,
    description: 'Tempo massimo per modificare un messaggio dopo l\'invio (secondi)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'message_history_retention',
    configSection: 'postal_system',
    configType: 'number',
    value: 365,
    defaultValue: 365,
    description: 'Durata di conservazione dei messaggi (giorni)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_delivery_enabled',
    configSection: 'postal_system',
    configType: 'boolean',
    value: true,
    defaultValue: true,
    description: 'Abilita il sistema di consegna postale',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_delay_simulation',
    configSection: 'postal_system',
    configType: 'boolean',
    value: true,
    defaultValue: true,
    description: 'Simula il ritardo di consegna della posta',
    isActive: true,
    metadata: { version: 1 },
  },

  // Message Types (8 JSON records - one per type)
  {
    configKey: 'postal_message_type_note',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      displayName: 'Bigliettino',
      description: 'Scambio rapido di bigliettini tra personaggi presenti',
      deliveryMode: 'realtime',
      deliveryMethod: 'to_person',
      requiresResidenceKnowledge: false,
      postageRequired: 0,
      maxLength: 200,
      requiresSealing: false,
      allowsReply: true,
      visibilityInPreview: 'first_line',
      availableToRoles: ['personaggio'],
      restrictedLocations: [],
      icon: '📝',
      allowMultipleRecipients: false,
      maxRecipients: 1,
    },
    defaultValue: {},
    description: 'Configurazione tipo messaggio: Bigliettino (realtime, gratuito)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_message_type_telegram',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      displayName: 'Telegramma',
      description: 'Messaggio urgente consegnato rapidamente',
      deliveryMode: 'scheduled_fixed',
      deliveryTiming: { fixedDelayMinutes: 20 },
      deliveryMethod: 'both_options',
      requiresResidenceKnowledge: false,
      postageRequired: 3,
      expressCostMultiplier: 1.5,
      maxLength: 500,
      requiresSealing: false,
      allowsReply: true,
      visibilityInPreview: 'subject_only',
      availableToRoles: ['personaggio'],
      restrictedLocations: [],
      icon: '⚡',
      allowMultipleRecipients: true,
      maxRecipients: 3,
    },
    defaultValue: {},
    description: 'Configurazione tipo messaggio: Telegramma (20min, 3 credits)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_message_type_letter',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      displayName: 'Lettera',
      description: 'Corrispondenza formale consegnata a domicilio',
      deliveryMode: 'daily_batch',
      deliveryTiming: { dailyDeliveryTimes: ['09:00', '15:00', '18:00'] },
      deliveryMethod: 'to_residence',
      requiresResidenceKnowledge: true,
      postageRequired: 1,
      expressCostMultiplier: 3,
      maxLength: 2000,
      requiresSealing: true,
      allowsReply: true,
      visibilityInPreview: 'subject_only',
      availableToRoles: ['personaggio'],
      restrictedLocations: [],
      icon: '✉️',
      allowMultipleRecipients: false,
      maxRecipients: 1,
    },
    defaultValue: {},
    description: 'Configurazione tipo messaggio: Lettera (daily batch, 1 credit)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_message_type_express_letter',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      displayName: 'Lettera Espressa',
      description: 'Consegna rapida tramite ragazzino messaggero',
      deliveryMode: 'messenger_boy',
      deliveryTiming: { variableDelayRange: { min: 10, max: 20 } },
      deliveryMethod: 'both_options',
      requiresResidenceKnowledge: false,
      postageRequired: 4,
      maxLength: 2000,
      requiresSealing: true,
      allowsReply: true,
      visibilityInPreview: 'subject_only',
      availableToRoles: ['personaggio'],
      restrictedLocations: [],
      icon: '🏃‍♂️',
      allowMultipleRecipients: false,
      maxRecipients: 1,
    },
    defaultValue: {},
    description: 'Configurazione tipo messaggio: Lettera Espressa (10-20min, 4 credits)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_message_type_postcard',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      displayName: 'Cartolina',
      description: 'Messaggio breve e aperto, economico',
      deliveryMode: 'daily_batch',
      deliveryTiming: { dailyDeliveryTimes: ['12:00', '18:00'] },
      deliveryMethod: 'both_options',
      requiresResidenceKnowledge: false,
      postageRequired: 0.5,
      expressCostMultiplier: 2,
      maxLength: 300,
      requiresSealing: false,
      allowsReply: true,
      visibilityInPreview: 'first_line',
      availableToRoles: ['personaggio'],
      restrictedLocations: [],
      icon: '🖼️',
      allowMultipleRecipients: true,
      maxRecipients: 5,
    },
    defaultValue: {},
    description: 'Configurazione tipo messaggio: Cartolina (daily batch, 0.5 credits)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_message_type_invitation',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      displayName: 'Invito Formale',
      description: 'Invito elegante per eventi sociali',
      deliveryMode: 'scheduled_variable',
      deliveryTiming: { variableDelayRange: { min: 240, max: 360 } },
      deliveryMethod: 'to_residence',
      requiresResidenceKnowledge: true,
      postageRequired: 2,
      expressCostMultiplier: 2,
      maxLength: 800,
      requiresSealing: true,
      allowsReply: true,
      visibilityInPreview: 'subject_only',
      availableToRoles: ['personaggio'],
      restrictedLocations: [],
      icon: '💌',
      allowMultipleRecipients: true,
      maxRecipients: 10,
    },
    defaultValue: {},
    description: 'Configurazione tipo messaggio: Invito Formale (4-6h, 2 credits, max 10 recipients)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_message_type_official_document',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      displayName: 'Documento Ufficiale',
      description: 'Comunicazioni ufficiali e legali',
      deliveryMode: 'scheduled_variable',
      deliveryTiming: { variableDelayRange: { min: 1440, max: 2880 } },
      deliveryMethod: 'to_residence',
      requiresResidenceKnowledge: true,
      postageRequired: 6,
      expressCostMultiplier: 3,
      maxLength: 5000,
      requiresSealing: true,
      allowsReply: false,
      visibilityInPreview: 'subject_only',
      availableToRoles: ['master', 'moderatore', 'gestore'],
      restrictedLocations: [],
      icon: '📜',
      allowMultipleRecipients: true,
      maxRecipients: 20,
    },
    defaultValue: {},
    description: 'Configurazione tipo messaggio: Documento Ufficiale (24-48h, 6 credits, master-only)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_message_type_diary',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      displayName: 'Diario Personale',
      description: 'Note private per uso personale',
      deliveryMode: 'no_delivery',
      deliveryMethod: 'self_only',
      requiresResidenceKnowledge: false,
      postageRequired: 0,
      maxLength: 10000,
      requiresSealing: false,
      allowsReply: false,
      visibilityInPreview: 'first_line',
      availableToRoles: ['personaggio'],
      restrictedLocations: [],
      icon: '📖',
      allowMultipleRecipients: false,
      maxRecipients: 1,
    },
    defaultValue: {},
    description: 'Configurazione tipo messaggio: Diario Personale (no delivery, 10k chars max)',
    isActive: true,
    metadata: { version: 1 },
  },

  // Global Settings (additional records beyond the 5 existing)
  {
    configKey: 'postal_settings_default_timezone',
    configSection: 'postal_system',
    configType: 'string',
    value: 'Europe/Rome',
    defaultValue: 'Europe/Rome',
    description: 'Timezone di default per calcoli orari consegna',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_settings_max_messages_per_day',
    configSection: 'postal_system',
    configType: 'number',
    value: 50,
    defaultValue: 50,
    description: 'Numero massimo messaggi inviabili per personaggio al giorno',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_settings_max_active_in_transit',
    configSection: 'postal_system',
    configType: 'number',
    value: 20,
    defaultValue: 20,
    description: 'Numero massimo messaggi contemporaneamente in transito',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_settings_cron_intervals',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      realtime_check: '*/1 * * * *',
      scheduled_delivery: '*/15 * * * *',
      daily_batch_morning: '0 9 * * *',
      daily_batch_afternoon: '0 15 * * *',
      daily_batch_evening: '0 18 * * *',
      messenger_boy_check: '*/5 * * * *',
    },
    defaultValue: {},
    description: 'Intervalli cron per job di consegna messaggi',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_settings_express_surcharge',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      enabled: true,
      multiplierRange: [1.5, 3],
    },
    defaultValue: { enabled: false, multiplierRange: [1, 1] },
    description: 'Configurazione sovrapprezzo express (enabled + range moltiplicatori costo)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'postal_settings_residence_system',
    configSection: 'postal_system',
    configType: 'json',
    value: {
      requiresDiscovery: true,
      allowsPublicDirectory: false,
      unknownAddressFee: 1,
    },
    defaultValue: {},
    description: 'Configurazione sistema residenze (discovery, directory pubblica, fee indirizzo sconosciuto)',
    isActive: true,
    metadata: { version: 1 },
  },

  // ── combat_system ───────────────────────────────────────────────
  {
    configKey: 'combat_damage_bonus_table',
    configSection: 'combat_system',
    configType: 'json',
    value: [
      { min: 2,   max: 64,  bonus: '-2' },
      { min: 65,  max: 84,  bonus: '-1' },
      { min: 85,  max: 124, bonus: '0' },
      { min: 125, max: 164, bonus: '+1d4' },
      { min: 165, max: 204, bonus: '+1d6' },
      { min: 205, max: 284, bonus: '+2d6' },
      { min: 285, max: 364, bonus: '+3d6' },
      { min: 365, max: 444, bonus: '+4d6' },
      { min: 445, max: 524, bonus: '+5d6' },
    ],
    defaultValue: [],
    description: 'Tabella bonus danno basato su FOR + TAG del personaggio',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'combat_unarmed_base_damage',
    configSection: 'combat_system',
    configType: 'number',
    value: 2,
    defaultValue: 2,
    description: 'Danno base inflitto con un attacco a mani nude (senza bonus FOR+TAG)',
    isActive: true,
    metadata: { version: 1 },
  },
  {
    configKey: 'combat_success_level_labels',
    configSection: 'combat_system',
    configType: 'json',
    value: {
      fumble: 'Maldestro',
      failure: 'Fallimento',
      normal: 'Normale',
      hard: 'Superiore',
      extreme: 'Estremo',
      critical: 'Critico',
    },
    defaultValue: {},
    description: 'Label italiane per i livelli di successo, usate nell\'output a video',
    isActive: true,
    metadata: { version: 1 },
  },

  // ── ticket_system ───────────────────────────────────────────────
  // Category: character_approval
  {
    configKey: 'ticket_category_character_approval',
    configSection: 'ticket_system',
    configType: 'json',
    value: {
      label: 'Approvazione Personaggio',
      description: 'Richiesta di approvazione scheda personaggio',
      department: 'administration',
      defaultPriority: 'medium',
      escalationThresholdHours: 48,
      whoCanCreate: 'all', // 'all' | 'approved_only' | 'staff_only'
      requiredStaffPermissions: ['characters.detail.approve'],
      autoClose: false,
      autoCloseMessage: null,
      autoCloseDelaySeconds: 0,
    },
    defaultValue: {},
    description: 'Configurazione categoria ticket: Approvazione Personaggio',
    isActive: true,
    metadata: { version: 1 },
  },

  // Category: character_edit
  {
    configKey: 'ticket_category_character_edit',
    configSection: 'ticket_system',
    configType: 'json',
    value: {
      label: 'Modifica Personaggio',
      description: 'Richiesta modifica personaggio post-approvazione (background, stats)',
      department: 'administration',
      defaultPriority: 'medium',
      escalationThresholdHours: 48,
      whoCanCreate: 'approved_only',
      requiredStaffPermissions: ['characters.detail.edit'],
      autoClose: false,
      autoCloseMessage: null,
      autoCloseDelaySeconds: 0,
    },
    defaultValue: {},
    description: 'Configurazione categoria ticket: Modifica Personaggio',
    isActive: true,
    metadata: { version: 1 },
  },

  // Category: quest_proposal
  {
    configKey: 'ticket_category_quest_proposal',
    configSection: 'ticket_system',
    configType: 'json',
    value: {
      label: 'Proposta Trama/Quest',
      description: 'Proposta trama o quest personalizzata',
      department: 'master',
      defaultPriority: 'low',
      escalationThresholdHours: 120,
      whoCanCreate: 'approved_only',
      requiredStaffPermissions: [],
      autoClose: true,
      autoCloseMessage: 'Grazie per la tua proposta! L\'abbiamo presa in carico e la valuteremo attentamente. Ti contatteremo in-game se necessario.',
      autoCloseDelaySeconds: 5,
    },
    defaultValue: {},
    description: 'Configurazione categoria ticket: Proposta Trama/Quest (auto-close)',
    isActive: true,
    metadata: { version: 1 },
  },

  // Category: game_bug_report
  {
    configKey: 'ticket_category_game_bug_report',
    configSection: 'ticket_system',
    configType: 'json',
    value: {
      label: 'Segnalazione Bug',
      description: 'Segnalazione bug in-game',
      department: 'technical',
      defaultPriority: 'high',
      escalationThresholdHours: 24,
      whoCanCreate: 'all',
      requiredStaffPermissions: [],
      autoClose: true,
      autoCloseMessage: 'Grazie per la segnalazione! Il bug è stato registrato e verrà analizzato dal team tecnico. Riceverai aggiornamenti se necessario.',
      autoCloseDelaySeconds: 5,
    },
    defaultValue: {},
    description: 'Configurazione categoria ticket: Segnalazione Bug (auto-close)',
    isActive: true,
    metadata: { version: 1 },
  },

  // Category: improvement_suggestion
  {
    configKey: 'ticket_category_improvement_suggestion',
    configSection: 'ticket_system',
    configType: 'json',
    value: {
      label: 'Suggerimento Miglioramento',
      description: 'Suggerimento per migliorare funzionalità esistenti',
      department: 'general',
      defaultPriority: 'low',
      escalationThresholdHours: 168,
      whoCanCreate: 'all',
      requiredStaffPermissions: [],
      autoClose: true,
      autoCloseMessage: 'Grazie per il tuo suggerimento! Lo abbiamo ricevuto e verrà discusso dal team. Apprezziamo il tuo contributo per migliorare l\'esperienza di gioco!',
      autoCloseDelaySeconds: 5,
    },
    defaultValue: {},
    description: 'Configurazione categoria ticket: Suggerimento Miglioramento (auto-close)',
    isActive: true,
    metadata: { version: 1 },
  },

  // Global ticket settings
  {
    configKey: 'ticket_system_settings',
    configSection: 'ticket_system',
    configType: 'json',
    value: {
      maxOpenTicketsPerCharacter: 5,
      allowReopenAfterDays: 7,
      autoEscalationEnabled: true,
      notifyStaffOnCreate: true,
      notifyCharacterOnReply: true,
    },
    defaultValue: {},
    description: 'Impostazioni globali sistema ticketing',
    isActive: true,
    metadata: { version: 1 },
  },

  // ── system ──────────────────────────────────────────────────────
  {
    configKey: 'system_maintenance_mode',
    configSection: 'system',
    configType: 'json',
    value: {
      enabled: false,
      message: '',
      allowedUsers: [],
      estimatedCompletion: null,
    },
    defaultValue: { enabled: false, message: '', allowedUsers: [], estimatedCompletion: null },
    description: 'Configurazione della modalità manutenzione del sistema',
    isActive: true,
    metadata: { version: 1 },
  },
];

async function main() {
  console.log('⚙️  System Configuration Seeder\n');

  const { client, db } = await getConnection();

  try {
    const collection = db.collection(COLLECTION);
    let seeded = 0;
    let skipped = 0;

    for (const config of ALL_CONFIGS) {
      const existing = await collection.findOne({ configKey: config.configKey });

      if (existing) {
        console.log(`  [SKIP] "${config.configKey}" already exists (v${existing.metadata?.version || '?'})`);
        skipped++;
        continue;
      }

      const now = new Date();
      await collection.insertOne({
        ...config,
        createdAt: now,
        updatedAt: now,
      });

      console.log(`  [OK]   "${config.configKey}" (${config.configSection}/${config.configType})`);
      seeded++;
    }

    console.log(`\n[DONE] Seeded: ${seeded}, Skipped: ${skipped}, Total: ${ALL_CONFIGS.length}`);
  } finally {
    await client.close();
  }
}

main().catch((err) => {
  console.error('[ERROR] Seeder failed:', err);
  process.exit(1);
});
